# Generated by Django 5.0 on 2023-12-15 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_dummymodel2_delete_dummymodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerAccount",
            new_name="CustomerMemberAccount",
        ),
    ]
