# Generated by Django 5.0 on 2023-12-15 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_rename_customeraccount_customermemberaccount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyModel2",
        ),
    ]
