# Generated by Django 5.0 on 2023-12-15 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_delete_dummymodel2"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="duration",
            field=models.CharField(default="2 years", max_length=100),
        ),
        migrations.AlterField(
            model_name="productinfo",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="backend.product"
            ),
        ),
    ]
