# Generated by Django 5.0 on 2023-12-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_product_duration_productinfo_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="policy_id",
            field=models.CharField(
                db_index=True, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
